### PR TITLE
Add ability to pass the selectedDate to DatePicker.initialise

### PR DESCRIPTION
**Pull request by icidasset**
Addresses #1 

Does this work for you @PanagiotisGeorgiadis ? I could also make a `initialiseWithDate` and keep the original `initialise` if you think that's a better idea?

### CODE REVIEW

**Comment by PanagiotisGeorgiadis** [comment]
@icidasset Yeap it totally addresses the issue! One thing I would change is to pass a `Maybe DateTime` instead of a `{ selectedDate: Maybe DateTime }` cause I think that since its going to be the only argument of `DateTime` type to be passed on our `DatePicker`, it should be clear enough.

**Comment by icidasset** [comment]
Aight sounds good @PanagiotisGeorgiadis
Updated it to your suggestion 👍 
Anything else you'd like me to do? (eg. bump version)

**Comment by PanagiotisGeorgiadis** [comment]
I feel pretty dumb @icidasset... I was just checking the API of the `DateRangePicker` module and it seems that in order for the user to set a `DateRange` I've introduced a [setDateRange](https://package.elm-lang.org/packages/PanagiotisGeorgiadis/elm-datepicker/latest/DateRangePicker#setDateRange) function which makes the implementation a bit more dynamic than just passing in a param on the `initialise` function. ( I've also introduced a (resetVisualSelection)[https://package.elm-lang.org/packages/PanagiotisGeorgiadis/elm-datepicker/latest/DateRangePicker#resetVisualSelection] function which resets it ).

Do you think that you would be able to implement it in this way cause I kind of see a benefit over the `initialise` function approach. I am so sorry for not seeing it earlier 😞

**Comment by icidasset** [comment]
@PanagiotisGeorgiadis No problem! ☺️ 

So, I'm not entirely sure I understand what you're saying. I assume you want me to implement a `setDate` function on the `DatePicker` module and leave the `initialise` function as is?

Also, the `resetVisualSelection` function is not applicable to the `DatePicker` module, right?

**Comment by PanagiotisGeorgiadis** [comment]
@icidasset Yeap exactly, let's implement a `setSelectedDate` function and leave the `initialise` as is. We could introduce a `resetSelectedDate` function ( which basically resets the selected date ), if we decide to create the `setSelectedDate` function like this:

```
setSelectedDate : DateTime -> Model -> Model
setSelectedDate = ....

resetSelectedDate : Model -> Model
resetSelectedDate = ....
```

This is more declarative than having the `setSelectedDate` accept a `Maybe DateTime`. 

@icidasset  Again I am so sorry that I didn't think of it earlier!

**Comment by icidasset** [comment]
@PanagiotisGeorgiadis Ayyeee, updated. I used different names than you suggested, which seem to fit better, but can change if you want to. Thanks.

**Comment by PanagiotisGeorgiadis** [comment]
@icidasset  🎉 Thanks for this, sorry to be obsessive, but I would really prefer that we stick with the originally proposed naming for two reasons: firstly that it leaves us consistent across the two modules that do similar things and secondly, so that the function name reflects the name of the record property in the model. Hope that's OK.

**Comment by icidasset** [comment]
@PanagiotisGeorgiadis No problem, updated 👍

**Comment by icidasset** [comment]
Thank you! ☺️

**Comment by PanagiotisGeorgiadis** [comment]
The release is complete! Thanks a lot @icidasset! 😄

**Pull request merged**
